#/c/Users/Pranav/Anaconda3/python
#python3.5

import numpy as np
import random as rand

def generate_matrix(rand_range,n_value):
    """
    randomly generate a NxN matrix using the random number generation range.
    :param rand_range: random number range to generate the matrix from. For example if 4, then the numbers 1,2,3,4 will be
    pseudo-randomly generated throught the NxN matrix.
    :param n_value: N value of the NxN matrix. For example if 4, then a 4x4 square matrix would be generated.
    :return:
    """
    matrix = np.empty([n_value,n_value])
    for x in range(rand_range):
        for y in range(rand_range):
            matrix[x][y] = rand.randrange(1, rand_range+1) % n_value+1

    return matrix

def check_for_musketeers(matrix, n):
    """
    This function is dedicated towards checking the matrix for 3 repeating values of the same number.
    First, we check horizontally for repeating values, then vertically. If we find any 3 concequtive numbers
    randomly generated by the generate_matrix function then immediately return invalid.
    :param matrix: randomly generated NxN matrix
    :param n: Row or Column value of the matrix, used to iterate over the values in the random matrix
    :return:
    """

    #Iterate horizontally
    musketeer_array = []
    for x in range(n):
        for y in range(n):
            value_1 = matrix[x][y]
            if y == 0:
                value_0 = value_1
                pass
            else:
                if value_1 == value_0:
                    musketeer_array.append(value_0)
                    if len(musketeer_array) == 3:
                        if (sum(musketeer_array)/3 == musketeer_array[0]):
                            return "Invalid"
                    musketeer_array.append(value_1)
                    value_0 = value_1
                else:
                    musketeer_array = []
    #Iterate Vertically
    musketeer_array = []
    for y in range(n):
        for x in range(n):
            value_1 = matrix[x][y]
            if x == 0:
                value_0 = value_1
                pass
            else:
                if value_1 == value_0:
                    musketeer_array.append(value_0)
                    if len(musketeer_array) == 3:
                        if (sum(musketeer_array)/3 == musketeer_array[0]):
                            return "Invalid"
                    musketeer_array.append(value_1)
                    value_0 = value_1
                else:
                    musketeer_array = []
    return "Valid"



if __name__== "__main__":
    rand_range= input("range of numbers to generate the random matrix out of:")
    rand_range = int(rand_range)
    n_value = input("Enter the N value of the NxN matrix:")
    n_value = int(n_value)
    matrix = generate_matrix(rand_range,n_value)
    print(matrix)
    ret = check_for_musketeers(matrix, n_value)
    print(ret)
